Vue.createApp({

    data(){
        return{
            books:[
                {
                    isbn:'978-4-7981-578\57-3',
                    title:'JavaScript逆引きレシピ',
                    price:2800
                },
                {
                    isbn:'978-4-7981-578\57-3',
                    title:'JavaScript逆引きレシピ',
                    price:2800
                },
                {
                    isbn:'978-4-7981-578\57-3',
                    title:'JavaScript逆引きレシピ',
                    price:2800
                },
                {
                    isbn:'978-4-7981-578\57-3',
                    title:'JavaScript逆引きレシピ',
                    price:2800
                },
                {
                    isbn:'978-4-7981-578\57-3',
                    title:'JavaScript逆引きレシピ',
                    price:2800
                },
            ]
        };
    }
}).mount('#app');